//
// Created by Richie on 2020/12/22.
//

#ifndef MULTIMEDIALEARNING_DECODE_STATE_H
#define MULTIMEDIALEARNING_DECODE_STATE_H

enum DecodeState {
    PREPARE,
    START,
    DECODING,
    PAUSE,
    STOP,
    FINISH
};

#endif //MULTIMEDIALEARNING_DECODE_STATE_H
