/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>

#ifndef _Included_cn_richie_ffmpeg_FFmpegNative
#define _Included_cn_richie_ffmpeg_FFmpegNative
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     cn_richie_ffmpeg_FFmpegNative
 * Method:    getVersion
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_cn_richie_ffmpeg_FFmpegNative_getVersion
        (JNIEnv *env, jclass cls) {

    return env->NewStringUTF("qwert");
}

#ifdef __cplusplus
}
#endif
#endif // _Included_cn_richie_ffmpeg_FFmpegNative
